version: '3.9'

services:
  leader-testnet-geth:
    build:
      dockerfile: docker/geth/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/geth:latest
    volumes:
      - leader-testnet-geth:/root
    environment:
      - MINER_PRIV_KEY
      - MINER_ADDRESS
      - GENESIS=l2-testnet
      # only used to get faster initial p2p connection setup
      - BOOTNODE=enode://61f076e9af396ecb5a0a8fb1a2c17491c3514f2abea0c228a3fcee49395339df2008fe201b37c7c0a565b775c5f8f5389b0b3de1701dc532c951a094af841cac@bootnode:30303
    command:
      --networkid 99
      --nodiscover
      --gcmode archive
      --unlock $MINER_ADDRESS
      --password /dev/null
      --allow-insecure-unlock
      --miner.gaslimit 300000
      --http
      --http.addr "[::]"
      --http.port 8545
      --http.corsdomain=*
      --http.vhosts=*
      --http.api eth,net,web3,txpool,miner,debug
      --nodekeyhex abebb96d7d9bbc99730439f230afd0008c0e0cb93eafb6874fecb256572252a4

  bootnode:
    depends_on:
      - leader-testnet-geth
    build:
      dockerfile: docker/geth/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/geth:latest
    volumes:
      - bootnode:/root
    environment:
      - MINER_ADDRESS
      - GENESIS=l2-testnet
      - BOOTNODE=enode://f28f5a7706e5aec836f3136feb7d5e7264a7f0da04ac4984f0ff2421ee1dd2b135894cf0d4f5ff8c412442b95b9bb0780a9c8a8c64de2d4a8c458586fdb20829@leader-testnet-geth:30303
    command:
      --networkid 99
      --syncmode full
      --nodiscover
      --gcmode archive
      --light.serve 100
      --light.nosyncserve
      --nodekeyhex be6e66a76b664af9debbe2f4b3b9f21257fcce34412e10dfe383aabca9b4a9c0

  server-testnet-geth:
    depends_on:
      - bootnode
    deploy:
      replicas: 2
    build:
      dockerfile: docker/geth/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/geth:latest
    environment:
      - MINER_ADDRESS
      - GENESIS=l2-testnet
      - BOOTNODE=enode://61f076e9af396ecb5a0a8fb1a2c17491c3514f2abea0c228a3fcee49395339df2008fe201b37c7c0a565b775c5f8f5389b0b3de1701dc532c951a094af841cac@bootnode:30303
    command:
      --networkid 99
      --syncmode light
      --nodiscover
      --http
      --http.addr "[::]"
      --http.port 8545
      --http.corsdomain=*
      --http.vhosts=*
      --http.api eth,net,web3,debug

  l1-testnet-geth:
    build:
      dockerfile: docker/geth/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/geth:latest
    volumes:
      - l1-testnet-geth:/root
    environment:
      - MINER_PRIV_KEY
      - MINER_ADDRESS
      - GENESIS=l1-testnet
    command:
      --networkid 98
      --unlock $MINER_ADDRESS
      --password /dev/null
      --allow-insecure-unlock
      --nodiscover
      --miner.gaslimit 40000000
      --mine
      --http
      --http.addr "[::]"
      --http.port 8545
      --http.corsdomain=*
      --http.vhosts=*
      --http.api eth,net,web3,debug
      --rpc.gascap 100000000000

  coordinator:
    init: true
    build:
      dockerfile: docker/coordinator/Dockerfile
      cache_from:
        - ghcr.io/privacy-scaling-explorations/zkevm-chain/coordinator-ci-cache:latest
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/coordinator:latest
    depends_on:
      - leader-testnet-geth
      - server-testnet-geth
      - l1-testnet-geth
      - prover-rpcd
    environment:
      - COORDINATOR_LISTEN=[::]:8545
      - COORDINATOR_RPC_SERVER_NODES=server-testnet-geth:8545
      - COORDINATOR_L2_RPC_URL=http://leader-testnet-geth:8545
      - COORDINATOR_L1_RPC_URL=http://l1-testnet-geth:8545
      - COORDINATOR_L1_BRIDGE=0x936a70c0b28532aa22240dce21f89a8399d6ac60
      - COORDINATOR_L1_PRIV=$MINER_PRIV_KEY
      - COORDINATOR_PROVER_RPCD_URL=http://prover-rpcd:8545
      - COORDINATOR_DUMMY_PROVER=${COORDINATOR_DUMMY_PROVER:-true}
      - COORDINATOR_ENABLE_FAUCET=true
      - COORDINATOR_CIRCUIT_NAME=super
      - COORDINATOR_UNSAFE_RPC=${COORDINATOR_UNSAFE_RPC:-false}

  prover-rpcd:
    init: true
    build:
      dockerfile: docker/prover/Dockerfile
      cache_from:
        - ghcr.io/privacy-scaling-explorations/zkevm-chain/prover-ci-cache:latest
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/prover:latest
    environment:
      - PROVERD_BIND=[::]:8545
      - PROVERD_LOOKUP=prover-rpcd:8545
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2500G

  coverage-l1:
    profiles:
      - dev
    image: ghcr.io/pinkiebell/develatus-apparatus:v0.4.7
    volumes:
      - .:/host:ro
    working_dir: /host
    environment:
      - RPC=http://l1-testnet-geth:8545

  coverage-l2:
    profiles:
      - dev
    image: ghcr.io/pinkiebell/develatus-apparatus:v0.4.7
    volumes:
      - .:/host:ro
    working_dir: /host
    environment:
      - RPC=http://leader-testnet-geth:8545

  dev:
    profiles:
      - dev
    depends_on:
      - leader-testnet-geth
      - server-testnet-geth
      - l1-testnet-geth
      - coverage-l1
      - coverage-l2
    build:
      dockerfile: docker/dev/Dockerfile
      cache_from:
        - ghcr.io/privacy-scaling-explorations/zkevm-chain/dev-ci-cache:latest
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/dev:latest
    volumes:
      - .:/app
      - dev-build-cache:/target:overlay
    environment:
      - COORDINATOR_LISTEN=[::]:8000
      - COORDINATOR_RPC_SERVER_NODES=server-testnet-geth:8545
      - COORDINATOR_L1_RPC_URL=http://l1-testnet-geth:8545
      - COORDINATOR_L2_RPC_URL=http://leader-testnet-geth:8545
      - COORDINATOR_L1_BRIDGE=0x936a70c0b28532aa22240dce21f89a8399d6ac60
      - COORDINATOR_L1_PRIV=$MINER_PRIV_KEY
      - COORDINATOR_DUMMY_PROVER=${COORDINATOR_DUMMY_PROVER:-true}
      - COORDINATOR_ENABLE_FAUCET=true
      # useful env vars if running the proverd inside the dev image
      - PROVERD_LOOKUP=dev:8001
      - COORDINATOR_PROVER_RPCD_URL=http://dev:8001
      - PROVERD_BIND=[::]:8001
      - COORDINATOR_CIRCUIT_NAME=pi
      - COORDINATOR_UNSAFE_RPC=true
      - COORDINATOR_VERIFY_PROOF=true
    working_dir: /app
    entrypoint: /sbin/getty
    command: '-'
    tty: true
    init: true
    deploy:
      resources:
        limits:
          memory: 2500G

  web:
    depends_on:
      - coordinator
    build:
      dockerfile: docker/web/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/web:latest

volumes:
  dev-build-cache:
  leader-testnet-geth:
  l1-testnet-geth:
  bootnode:
