apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-sandbox
  namespace: chain-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME-sandbox
  template:
    metadata:
      labels:
        app: $APP_NAME-sandbox
    spec:
      containers:
      - name: $APP_NAME-sandbox
        command: [ "/bin/bash" ]
        args: [ "-c","./target/release/prover_rpcd --bind 127.0.0.1:8546 " ]
        image:  $REGISTRY/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 8
            memory: 32Gi
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        - name: data
          mountPath: /data/blocks
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8546
        env:
          - name: TZ
            value: GMT
          - name: RUST_LOG
            value: pallet_evm=debug,pallet_ethereum=debug
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: data
        persistentVolumeClaim:
          claimName: vmchain-ssd-pvc
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - $APP_NAME-sandbox
              topologyKey: "kubernetes.io/hostname"
  strategy:
    type: Recreate
